language: node_js
node_js:
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- '6.0'
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: XO4isromVFV7qpNYvqCZ3RXkp1xO+CGDH26RafVeD8zrhkynxN+sihOmE7jJRZJzH1bM945pyCJe4iaAprYnBbV2aKaBCOIjIoeGx1FMi3Z6daYM2CVaGFix1Emwfp1rUpJh76hLWeSrfwKild9yyeHDlpxYvCTnCRKPBkDuIBk=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: WPX1vEJ58FJKttn7sqNfHuYfLZr8SsKLGrQG2iTG8ayV/NXisSF38SJj5R3WpSCwAgegQf7s7maj+sL9QEuOdthhiuYprO4F5/LWzI8Qq14uTDUsZ/BlMN7yEhzet+PYXo7OI3CbWj0A3fuyUIHtzKQ8rCmZxkzx3ZXHD69lTRk=
    file:
      - "spache.js"
      - "spache.min.js"
    on:
      tags: true
      node: '6.0'
