language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GLY2fJ1GzUwHbfjKpwsH+jxkv9v9zLZSUoLZp1MvOV3XC9CDbgzfBFMBoEtbHjPgdwrTFaKtRuYwKoLZ5J0154br+MqxE7+A5EPgVVPbXFa0P/9YsJTRcCrgclZ04aIl+nBI0fkzefUBbCkyJ5ad19bpgK148mrP0U1xN8A8HJ0=
  file:
    - 'spache.js'
    - 'spache.min.js'
  on:
    tags: true
